version: "3"

services:
  bot:
    image: nayzbysodium/soundwave-bot:latest
    restart: on-failure
    environment:
      DISCORD_TOKEN: "secret"
      DISCORD_ID: "secret"
      DISCORD_SECRET: "secret"
      DISCORD_OAUTH_URL: "secret"
      CALLBACK_URL: "secret"
      JWT_SECRET: "secret"
      MONGO_URL: "secret"
      SPOTIFY_ID: "secret"
      SPOTIFY_SECRET: "secret"
      SPOTIFY_OAUTH_URL: "secret"
      SPOTIFY_REDIRECT_URL: "secret"
      CLIENT_URL: "secret"
    labels:
      - traefik.enable=true
      - traefik.http.routers.soundwave-api.rule=Host(`api.soundwave.nayz.fr`)
      - traefik.http.routers.soundwave-api.entrypoints=websecure
      - traefik.http.routers.soundwave-api.service=csoundwave-api
      - traefik.http.services.soundwave-api.loadbalancer.server.port=5000
      - traefik.http.routers.soundwave-api.tls.certresolver=production
    expose:
      - 5000
  dashboard:
    image: nayzbysodium/soundwave-dashboard:latest
    restart: on-failure
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.soundwave-dashboard.rule=Host(`dashboard.soundwave.nayz.fr`)
      - traefik.http.routers.soundwave-dashboard.entrypoints=websecure
      - traefik.http.routers.soundwave-dashboard.service=csoundwave-dashboard
      - traefik.http.services.soundwave-dashboard.loadbalancer.server.port=3000
      - traefik.http.routers.soundwave-dashboard.tls.certresolver=production

networks:
  webgateway: