version: "3"

services:
  bot:
    image: nayzbysodium/soundwave-bot:latest
    restart: on-failure
    environment:
      DISCORD_TOKEN: "secret"
      DISCORD_ID: "secret"
      DISCORD_SECRET: "secret"
      DISCORD_OAUTH_URL: "secret"
      CALLBACK_URL: "secret"
      JWT_SECRET: "secret"
      MONGO_URL: "secret"
      SPOTIFY_ID: "secret"
      SPOTIFY_SECRET: "secret"
      SPOTIFY_OAUTH_URL: "secret"
      SPOTIFY_REDIRECT_URL: "secret"
      CLIENT_URL: "secret"
    expose:
      - 5000
  dashboard:
    image: nayzbysodium/soundwave-dashboard:latest
    restart: on-failure
    expose:
      - 3000